services:
- type: web
  name: mega-cdn
  env: node
  plan: free
  buildCommand: npm install && npm run build
  startCommand: npm start
  autoDeploy: true
  envVars:
    - key: MEGA_ACCOUNT
      value: "email:password;email:password"
    - key: PORT
      value: "3000"
    - key: MAX_FILE_SIZE
      value: "100"
    - key: MAX_FILES
      value: "10"
    - key: CACHE_TTL
      value: "3600"
    - key: MAX_REQUESTS
      value: "100"
    - key: RATE_LIMIT
      value: "1 minute"
    - key: AUTHORIZATION
      value: "false"
    - key: AUTH_TOKEN
      value: "CustomApikey"
    - key: AUTO_DELETE
      value: "false"
    - key: DELETE_TIME
      value: "1440"
    - key: TEMP
      value: "memory"
    - key: DATABASE_URL
      value: ""
    - key: FILENAMES
      value: "false"